### ISSUE TITLE
JK-PB2A16S20P Add temperature sensors 3 and 4

### ISSUE THREAD

**Issue by tlamoureux24** [mr-manuel/venus-os_dbus-serialbattery#50]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add battery temperature sensors number 3 and 4 in addition to numbers 1 and 2 and mosfet temperature.

**Comment by KoljaWindeler** [comment]
Hey @mr-manuel, how motivating are command-tickets like that for you? 
Also: how much are people paying you for your work :) ?

I can take care of this though

**Comment by tlamoureux24** [comment]
> Hey @mr-manuel, how motivating are command-tickets like that for you? Also: how much are people paying you for your work :) ?
> 
> I can take care of this though

hello, I don't know if this is ironic, humorous or something else ..... sorry I'm French and I use deepl ......
I posted this enhancement request with the proper form I think because I think it can improve the driver for everyone.
If my request is badly formulated I apologize.
Unless I'm mistaken, temperature values are used in some driver calculations, and what I've noticed on my battery, which is a 16-cell vertical pack, is that the batteries at the top are sometimes 2 to 3 degrees hotter than those at the bottom, so this can have some influence.
Sorry for the inconvenience, my request can be closed.

**Comment by KoljaWindeler** [comment]
well maybe I should react a little easier, I'm maintaining some other projects and receive quite some "why is this not working, fix it!" messages .. and I guess I also speak for other open source contributor that we all do this work at our free time so a little "hey guys, thanks for the work, it would be awesome if you could add XYZ" would be nice ..

but anyway .. I already have temp3 and temp4 working and it is a good idea to add it .. will send out an update soon

**Comment by tlamoureux24** [comment]
You're right, I should have phrased it more politely and I apologize for that, and you're also right, opensource developers are often not thanked enough for their work.
I don't know how to code, but I think I've contributed a little to my small level of knowledge by reporting bugs with all the information I can and testing everything I'm asked to.
I've already had the opportunity to thank mr-manuel several times for his work and his time (please see https://github.com/mr-manuel/venus-os_dbus-serialbattery/issues/43 and https://github.com/mr-manuel/venus-os_dbus-serialbattery/issues/48 )

In any case, thank you for your time and your work on this and other projects.
Have a nice day

**Comment by KoljaWindeler** [comment]
should be working .. 
![image](https://github.com/mr-manuel/venus-os_dbus-serialbattery/assets/471314/9d80b5f0-9d19-41e2-92c8-dcb3fa33d3ca)
and 
![image](https://github.com/mr-manuel/venus-os_dbus-serialbattery/assets/471314/9786f7ae-0d0f-4b96-a9d6-2d8242a2622f)

pull request submitted https://github.com/mr-manuel/venus-os_dbus-serialbattery/pull/53, please reopen if you have an issue
Kolja

**Comment by tlamoureux24** [comment]
Thank you very much @KoljaWindeler  and @mr-manuel for the work and the time paste on this enhancement.
