### ISSUE TITLE
Support for 500kbps CAN bus connection

### ISSUE THREAD

**Issue by NickRoberts174** [mr-manuel/venus-os_dbus-serialbattery#92]
### Is your feature request related to a problem? Please describe.

** Re-upload of issue #1135 (https://github.com/Louisvdw/dbus-serialbattery/issues/1135) **

After much trial and error, trying to get the driver to communicate with my 2 batteries in parrallel, running Daly smart BMS's with WNT interface boards, I found a clue in Mr. Manuel's version that you have to select a 250kbps port (which the WNT boards don't support - they run on 500kbps), which was why the driver doesn't appear to work on CAN bus for me.

![image](https://github.com/user-attachments/assets/137839ee-567c-4bb3-98a1-183f7cc95692)

![image](https://github.com/user-attachments/assets/b9355484-b1e0-46cd-a932-4cc1789c60e5)

### Describe the solution you'd like

Is there any way that the driver could be selected to work on 500kbps so that the Daly WNT boards are compatible please?

### Describe alternatives you've considered

I have tried using 2x off RS485 to USB serial adapters, one in each battery, but the driver will only work with one at a time. I have tried all ways of trouble shooting this and have had no success, I believe CAN bus would be the neatest solution as it removes the need for additional hardware which would become failure points of failure. Below are the combinations I have tried. it is also worth noting i have tried countless combinations of addressing the BMS's, either via dip switches, on the Daly software or in the driver settings with no luck. 

![image](https://github.com/user-attachments/assets/e577d3ff-2873-4431-b465-1dc1e0a39295)
![image](https://github.com/user-attachments/assets/fb6de013-e508-49d2-b23d-0dbcfac226c5)
![image](https://github.com/user-attachments/assets/769cbe7d-2e5c-43e7-845f-bcef065fe956)
![image](https://github.com/user-attachments/assets/2e6a2fef-d1af-437f-a3a0-5a65c497dd20)
![image](https://github.com/user-attachments/assets/f495f925-57f6-4249-ade8-c832f6d734ae)
![image](https://github.com/user-attachments/assets/c437ad9a-0467-4f49-adf2-e9300d2b5497)

### Additional context

Victron Multiplus 2 48/5000/70
Victron Cerbo GX 
Victron Smart Solar Charge Controller MPPT 250/100
Battery 1 - 18S 280AH LiFePo4 with Daly Smart BMS, WNT interface, Daly active balancer and Daly parallel protection board 
Battery 2 - 18S 280AH LiFePo4 with Daly Smart BMS, WNT interface, Daly active balancer and Daly parallel protection board 

Batteries are in parallel

**Comment by mr-manuel** [comment]
Please open a separate support issue for your RS485 problem, since I need a few details to help you with that. So we can solve both.
